############# English navigation ##############

# main menu
[[main]]
name = "처음으로"
url = "/"
weight = 1

[[main]]
name = "소개"
url = "about/"
weight = 2

[[main]]
name = "블로그"
url = "blog/"
weight = 3

[[main]]
name = "공지사항"
url = "categories/공지사항/"
weight = 4

[[main]]
name = "자주묻는질문"
url = "categories/자주묻는질문/"
weight = 5

# footer menu
[[footer]]
name = "소개"
url = "about/"
weight = 1

[[footer]]
name = "블로그"
url = "blog/"
weight = 2

[[footer]]
name = "이용약관"
url = "privacy-policy/"
weight = 3
